version: '3.8'

services:
  frontend:
    container_name: cin3club-frontend
    build:
      context: ./packages/app-frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      - VITE_BASE_URL=http://localhost:3000
      - BACKEND_URL=http://cin3club-backend:3000
    volumes:
      - ./packages/app-frontend/src/:/home/node/src
      - ./packages/app-frontend/index.html/:/home/node/index.html
      - /home/node/node_modules
    ports:
      - '8000:8000'
  backend:
    container_name: cin3club-backend
    build:
      context: ./packages/app-backend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/cin3club
      - BCRYPT_SALT_ROUNDS=11
      - COOKIE_KEY=1111111111111111111111111111111111
      - FRONTEND_URL=http://cin3club-frontend:8000
      - FRONTEND_URL_DEV=http://localhost:8000
      - LOG_LEVEL=debug
    volumes:
      - ./packages/app-backend/lib/:/app/lib
      - ./packages/app-backend/server/:/app/server
      - ./packages/app-backend/package.json/:/app/package.json
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: cin3club-db
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=cin3club
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    restart: always
