version: '3.8'

services:
  ui:
    container_name: kino-ui
    build:
      context: ./packages/ui
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./packages/ui/src/:/app/src
      - ./packages/ui/package.json/:/app/package.json
    ports:
      - '8000:8000'
  api:
    container_name: kino-api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
      target: dev
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/kino
      - BCRYPT_SALT_ROUNDS=11
      - COOKIE_KEY=1111111111111111111111111111111111
      - CLIENT_URL=http://localhost:8000
    volumes:
      - ./packages/api/lib/:/app/lib
      - ./packages/api/server/:/app/server
      - ./packages/api/package.json/:/app/package.json
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: database-docker
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=kino
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    restart: always
