version: '3.8'

services:
  frontend:
    container_name: kino-frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./packages/frontend/src/:/app/src
      - ./packages/frontend/package.json/:/app/package.json
      - ./packages/frontend/tailwind.config.cjs/:/app/tailwind.config.cjs
      - ./packages/frontend/index.html/:/app/index.html
    ports:
      - '8000:8000'
  backend:
    container_name: kino-backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/kino
      - BCRYPT_SALT_ROUNDS=11
      - COOKIE_KEY=1111111111111111111111111111111111
      - CLIENT_URL=http://localhost:8000
      - LOG_LEVEL=debug
    volumes:
      - ./packages/backend/lib/:/app/lib
      - ./packages/backend/server/:/app/server
      - ./packages/backend/package.json/:/app/package.json
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: database-docker
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=kino
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    restart: always
